// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohilmcuwtpatnihbeofa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oaWxtY3V3dHBhdG5paGJlb2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODMzOTUsImV4cCI6MjA2MTM1OTM5NX0.BzzbH4dh_6u2N3as2MBjw7f49cSOBF79XxASbgZNB5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);